### ISSUE TITLE
[Google Shopping API] `link` and `links` are missing even though `direct_link=true` is included

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1889]
One of our users reported that the `link` is not present for some products even though the `direct_link=true` parameter is included. I couldn't recreate the issue on my side, but this might come up more often in the future if we don't address it.

Product missing `link` and `links`:
<img width="1333" alt="image" src="https://github.com/user-attachments/assets/21cf78ed-cd26-4b27-8636-e2fe4ce2a996">

[Inspect](https://serpapi.com/searches/66d188279e5bd59d9b196633/inspect)
[Front](https://app.frontapp.com/open/cnv_1ckowvmk)

**Comment by mikemorcerf** [comment]
Thank you for creating the ticket @marm123.
I couldn't replicate this bug.
Did you have more people reaching out about this issue?

**Comment by marm123** [comment]
Sorry for the late response @mikemorcerf. It was the only time someone reported it, I believe. I wasn't able to recreate it myself too.

**Comment by mikemorcerf** [comment]
Thanks @marm123. Let's wait to see if this problem will be reported again before doing more investigating.

**Comment by schaferyan** [comment]
Another customer reached out about this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000072126?view=List) | [Inspect](https://serpapi.com/searches/6735086963a844344aaa5b15/inspect)

**Comment by NateSkiles** [comment]
Another high-volume customer reached out about this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000072168?view=List) | [Inspect](https://serpapi.com/searches/67364611ca6f0c16fcc38a45/inspect)

---

[Playground](https://serpapi.com/playground?engine=google_shopping&q=coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&direct_link=true&num=100&device=desktop&direct_link=true&newPara=direct_link)

![image](https://github.com/user-attachments/assets/d2444766-ca01-4851-9194-fe808062fc33)

**Comment by sonika-serpapi** [comment]
Another customer reached out about this.

[Front](https://app.frontapp.com/open/cnv_1dv71ggs?key=ceXesTYpEhMFkagGeGLdjRIUUGcXEw7u)

**Comment by NateSkiles** [comment]
Another user reached out about this:

[Front](https://app.frontapp.com/open/cnv_1dv7chuk?key=y3J4MOehdAN2YWJ8ZPK3TyS0a0EfODbd)

**Comment by schaferyan** [comment]
@mikemorcerf I'm just tagging you to make sure you're aware of the increasing reports of this issue, since you had started working on it previously.

**Comment by mikemorcerf** [comment]
Thank you for tagging me, @schaferyan. I'll look into it.

**Comment by schaferyan** [comment]
Another customer reported this:

[Intercom](https://app.frontapp.com/open/msg_2jxnognw?key=mdqGr2bw8t1hji-6eL9VvYdaEZvjAbOd)

**Comment by hilmanski** [comment]
A user reported this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000072176?view=List)

**Comment by Krugloff** [comment]
The coffee example from @NateSkiles started working for me after I sent a request with no_cache.

**Comment by mikemorcerf** [comment]
@NateSkiles Yes, it's working again. Now I'm working on a change that I believe will generate more consistent results.

**Comment by Krugloff** [comment]
https://serpapi.com/searches/22b134190b08b273/6736f57aa775f2df5421732d.html

<img width="1451" alt="image" src="https://github.com/user-attachments/assets/6df2931f-bf29-4aca-b482-63590b5776b9">

The direct-links are here.

**Comment by mikemorcerf** [comment]
Thank you @Krugloff. These direct_links are actually injected into the html by us. If you look at the Google Shopping Page this div with #direct-links won't be there.

**Comment by hilmanski** [comment]
A customer reported this issue.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000067237?view=List)

**Comment by mikemorcerf** [comment]
@NateSkiles, @hilmanski, @schaferyan, @sonika-serpapi, @marm123,
I spoke with @aciddjus and we came to the conclusion that unfortunately my solution is not viable because it uses one request per product to retrieve all `direct_links`.
I closed my PR [Google Shopping API - use GET request to fetch direct_links](https://github.com/serpapi/SerpApi/pull/5543), but it can still be used as a reference.
I'll unassign myself for this ticket.

**Comment by NateSkiles** [comment]
@KBCG Apologies for the confusion; we are currently still investigating this issue.

I did want to mention that this issue appears to be sporadic, as I'm seeing links returned at the moment:

https://serpapi.com/playground?engine=google_shopping&q=playstation+5&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&direct_link=true&num=100&device=desktop&direct_link=true&newPara=direct_link

Additionally, if links are not returned for a specific item, you can also retrieve them via the Google Products API:

https://serpapi.com/google-product-api

https://serpapi.com/playground?engine=google_product&product_id=4887235756540435899&gl=us&hl=en

We'll be sure to ping you once this issue has been resolved. In the meantime, please let us know if you have any questions.

**Comment by hilmanski** [comment]
The high-volume customer followed up on this issue.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000067237?view=List)

**Comment by hilmanski** [comment]
Another user asked about this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000072931?view=List)

**Comment by martin-serpapi** [comment]
Another customer reached out about it:

[Front](https://app.frontapp.com/open/cnv_1ckowvmk?key=AW-GmJjmRlMmBGHe61Yi7Fqfr0lamoRM)

**Comment by martin-serpapi** [comment]
Another user reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000073859?view=List)

**Comment by NateSkiles** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000073871?view=List)

[Search Inspect 1](https://serpapi.com/searches/883dd00ef34c499e/677fce3726330e3200b89c53.json) | [Search Inspect 2](https://serpapi.com/searches/f8fa74db4485294b/677fa4f35dbb40c4f9ec0d01.json)

**Comment by martin-serpapi** [comment]
Another customer requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000073893?view=List)

**Comment by martin-serpapi** [comment]
Another user reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000073897?view=List)

**Comment by martin-serpapi** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000073888?view=List)

**Comment by hilmanski** [comment]
A customer reported this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000073937?view=List)

**Comment by hilmanski** [comment]
Maybe we should mention this issue in the documentation?

**Comment by hilmanski** [comment]
A user reported this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000073934?view=List)

**Comment by marm123** [comment]
An Enterprise Customer reached out about this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000073871?view=List)

@Krugloff, are there any updates you can share? Thank you in advance!

**Comment by Krugloff** [comment]
@marm123 I'm afraid my update won't make anyone happy. It seems Google has changed the API, and the new implementation will be more expensive than the current one, as it will require a new engine for extracting direct links one by one :(

**Comment by Krugloff** [comment]
As far as I can tell, we're currently returning zero direct_links.

**Comment by NateSkiles** [comment]
Another customer asked about this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000073999?view=List)

**Comment by KBCG** [comment]
@Krugloff  -- ditto to you on your comment. This is very critical for us

**Comment by martin-serpapi** [comment]
Thank you for your feedback @KBCG , and apologies for the inconvenience this is causing. We'll get back to you as soon as it is resolved.

**Comment by marm123** [comment]
Another user reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000074028?view=List)

**Comment by schaferyan** [comment]
One of the Enterprise customers who reported this mentioned it seems to be fixed now.  I've verified in the Playground that at least most products seem to have `link` and `links` now when `direct_link` is true. Since we haven't merged a fix for this, I'm assuming Google reverted changes on their side. 

[Playground](https://serpapi.com/playground?engine=google_shopping&q=Coffee&direct_link=true&direct_link=true&newPara=direct_link)

**Comment by schaferyan** [comment]
The original sporadic issue of some products missing links is not resolved, as it looks like there is still the occasional missing `link`:

<img width="1364" alt="Image" src="https://github.com/user-attachments/assets/2ebffbff-04d3-4862-affa-e057c551ac52" />

But this was after trying several other searches and only seeing results with `link` and `links`, a significant improvement from  `links`missing from all results.

**Comment by schaferyan** [comment]
I've updated users who reported this in December or later. I believe earlier reports were about the intermittent missing `link` and `links` which we are still working on.

**Comment by schaferyan** [comment]
@Krugloff a customer reported they are once again getting 0 `link` or `links` fields in Google Shopping results, even with `direct_link`.

I've also verified this with our "Coffee" example in the Playground:

[Playground](https://serpapi.com/playground?engine=google_shopping&q=Coffee&direct_link=true&direct_link=true&newPara=direct_link)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000075067?view=List)

**Comment by sonika-serpapi** [comment]
Another customer reported seeing no links in the response:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000075068?view=List)

**Comment by hilmanski** [comment]
Another customer reported this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000075075?view=List)

**Comment by Krugloff** [comment]
@sonika-serpapi @hilmanski @schaferyan Thank you. Yes, unfortunately, Google is no longer returning data in batches. We'll monitor the situation for a few days.

> An alternate way to get the link as of now is to query our Product API using the serpapi_product_api field in the response, and then getting the direct_link from there.

I feel like we should start recommending our `Google Immersive Product API` and `serpapi_immersive_product_api` instead. What do you think?

**Comment by Krugloff** [comment]
> is there a reason you think the Immersive Product API might be a better option for this?

@schaferyan As far as I know Immersive Product API is based on the actual requests sent from live pages on click to product card.

**Comment by kdmny** [comment]
Here's another example, hope its helpful: https://serpapi.com/searches/43fec90a89ed7180/67a624233d07d2bcd103f8ad.json

**Comment by hilmanski** [comment]
The previous customer reported this:
- [Front](https://app.frontapp.com/inboxes/teams/folders/22722140/open/109858914908)
- [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000075075?view=List)

**Comment by KBCG** [comment]
@kdmny @Krugloff @hilmanski @hilmanski @mikemorcerf @marm123  this is happening again.... it works then it doesnt.. can you all update on what is been done to fix ?

**Comment by marm123** [comment]
Hi @KBCG, thanks for reaching out. We're still assessing the issue and trying to find a proper solution, but I don't have any updates for now.

The current solution is to use our Google Immersive Product or Google Product APIs. Please check the documentation:

https://serpapi.com/google-immersive-product-api
https://serpapi.com/google-product-api

Although these solutions are not perfect, as both require additional API calls for each product to gather links, they are the best we can offer at the moment. However, we'll continue working on a proper solution and make sure we follow up with you as soon as there is any movement on that topic.

Thank you for your patience, and I'm sorry for the inconvenience.

**Comment by ReefPig** [comment]
@marm123 how can we get to the page_token via a google search hit? It only appears to be returned by the google shopping search.

**Comment by schaferyan** [comment]
Hi @ReefPig, when immersive product results are returned via the Google Search API, you can retrieve the `page_token` from the `immersive_product_page_token` key:

https://serpapi.com/playground?q=laptops&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&google_domain=google.com

<img width="1408" alt="Image" src="https://github.com/user-attachments/assets/1dfd673c-8385-45c2-be4d-4569b7f92197" />

If you have any further questions, please reach out to support@serpapi.com for assistance.

**Comment by ReefPig** [comment]
But what about in this state:
https://serpapi.com/playground?q=macbook+pro+m4&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en

**Comment by martin-serpapi** [comment]
Hi @ReefPig , thank you for sharing this example. I investigated it and it seems that `immersive_products` results are not returned in the response for your search term. 

You can instead try to perform this search using our Google Shopping API instead:

https://serpapi.com/playground?engine=google_shopping&q=macbook+pro+m4&newPara=direct_link

You can then use the `product_id` values for each of the `shopping_results` entries in the response to send a request to our Google Product API and retrieve the direct link of the product:

https://serpapi.com/playground?engine=google_product&product_id=6458501044423237976&gl=us&hl=en

If you need help with anything else,  please reach out to [support@serpapi.com](mailto:support@serpapi.com) for further assistance.

**Comment by alexbarron** [comment]
Another report:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000075376?view=List)

**Comment by martin-serpapi** [comment]
Another report:

[Front](https://app.frontapp.com/open/cnv_1ckowvmk?key=AW-GmJjmRlMmBGHe61Yi7Fqfr0lamoRM)

**Comment by schaferyan** [comment]
Another report of this:

[Front](https://app.frontapp.com/open/msg_2n3qjgpo?key=AW-GmJjmRlMmBGHe61Yi7Fqfr0lamoRM)

**Comment by rsadr1ev** [comment]
hi @sonika-serpapi @Krugloff is there any ETA you could share for the fix (if this is going to be fixed at all)? While pulling direct_link from serpapi_product_api works, it increases costs 40x for extracting 1 page of search results from google_shopping, while makes it cost prohibitive for our use case.

**Comment by Krugloff** [comment]
Hi @rsadr1ev, unfortunately, we can't share any ETA. This change originates from Google's side.

**Comment by sonika-serpapi** [comment]
Hi @rsadr1ev, thanks for reaching out. Unfortunately, we don't have an ETA as of now. I understand that the alternate solution we suggested is not perfect, as it requires additional API calls for each product to gather links, but it is the best we can offer at the moment. 

Unfortunately, as @Krugloff mentioned, the issue arises from Google's changes, and finding a fix is not very straightforward in this case. We'll continue working to find a proper solution and we will follow up with you as soon as we implement it.

Thank you for your patience, and I'm sorry for the inconvenience.

**Comment by alexbarron** [comment]
A high volume customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000075801?view=List)

**Comment by NateSkiles** [comment]
Another high-volume customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000075882?view=List)

**Comment by KBCG** [comment]
@kdmny @schaferyan @sonika-serpapi  @martin-serpapi 

Hello, 

we are still waiting on a workaround. To be clear for normal google results (non advertisement) we are NOT getting the direct link like the walmart.com/whatever link even when the Direct Link is on.  Can you guys please advise when this will be patched up, and or what is a current working workaround?

**Comment by NateSkiles** [comment]
Another customer reported this:

[Front](https://app.frontapp.com/open/cnv_1erp6tb0?key=E16N0dp8wdrBu-D7CFfM8WfMPP3PvWj2)

**Comment by marm123** [comment]
Hi @roman-bartusiak-yohana, I'm very sorry for that. We currently don't have a better solution, but we'll make sure to post updates here if anything changes.

Once again, I apologize for the trouble.

**Comment by 99xAgency** [comment]
We are able to workaround it:

`async def get_redirect_url(session, url): res = await session.head(url, allow_redirects=True) return res.url`

But we would prefer to get the direct url from API call in the first place.

**Comment by hilmanski** [comment]
Thank you very much for sharing your findings @99xAgency . We'll let you know once we have any update on this. Unfortunately, at the moment, Google has stopped sharing these links. Due to the nature of web scraping, we can only provide the data when it's available on the original site.

**Comment by hilmanski** [comment]
A user is interested in this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000076496?view=List)

**Comment by sonika-serpapi** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000076534?view=List)

**Comment by DanielLDorn** [comment]
I have set direct_link = true, but I still don't get a 'link' in the serpapi shopping results, so @99xAgency 's solution doesn't work for me.

**Comment by sonika-serpapi** [comment]
@DanielLDorn Thank you for letting us know. We'll let you know once we have an update on this. Unfortunately, as of now, we are not able to provide the links because Google has stopped sharing these links.

**Comment by 99xAgency** [comment]
@sonika-serpapi see the screenshot, if you are after mainly the shopping results then choosing Tablet or Mobile gives a lot more results than desktop. Also note the "link" present in the json, and if you use the code I mentioned earlier you should be able to get the direct link to product page. I just wish SerpAPI can integrate on their side but it would increase response time as each link would need to be visited to see the redirect URL. They could offer this as an option for people who are willing to wait. 

![Image](https://github.com/user-attachments/assets/4ea51bf4-50d1-450f-956f-b1ee52eacd9c)

**Comment by sonika-serpapi** [comment]
Thank you @99xAgency for elaborating on that. This approach seems to use one request per product to retrieve all `direct_links`, which is quite a bit of requests and time as you mentioned. We'll take it into consideration as we think of a solution for this though. 

@hilmanski tagging you for reference, as you asked them this question.

**Comment by martin-serpapi** [comment]
Another user requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000076942?view=List)

**Comment by rsadr1ev** [comment]
@sonika-serpapi @99xAgency  can you please share the full search query? Are you using Google Shopping API? I am not able to replicate this and get the "link" field in the playground.

**Comment by NateSkiles** [comment]
@rsadr1ev I did some testing with this and found @99xAgency's workaround only works for Google Searches that return `inline_shopping_results`. Here's an example search from our playground:

<img width="1578" alt="Image" src="https://github.com/user-attachments/assets/209d2e76-665b-4814-acfd-bf56465d3ba5" />

https://serpapi.com/playground?engine=google_shopping&q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=tablet&google_domain=google.com&newPara=chips+as_sitesearch+votes+site+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source+direct_link

However, the results returned in `shopping_results` do not include direct links, but Google product links instead (as outlined in this issue).

<img width="1573" alt="Image" src="https://github.com/user-attachments/assets/fa29ca37-92ec-4a8f-972d-71a27c631cb8" />

Meaning, while you can retrieve the direct link using a redirect for `inline_shopping_results`, the `shopping_results` still require an API call to our Google Immersive Product API ([docs](https://serpapi.com/google-immersive-product-api)) to obtain direct links, as outlined by @martin-serpapi in this [comment](https://github.com/serpapi/public-roadmap/issues/1889#issuecomment-2650154591).

I hope this makes sense, but if you have any questions, please feel free to reach out to us at contact@serpapi.com.

**Comment by 99xAgency** [comment]
@NateSkiles So we will have to make two calls to the API, one to get "shopping_results" and another to get direct links via Google Immersive Product API, which significantly increases each query's cost. Since each "shopping_results" response could potentially have over 20 results, this will create an additional 20 calls to Google Immersive Product API, exhausting our monthly API usage super quickly.

**Comment by marm123** [comment]
@99xAgency, you are correct. This solution is definitely more expensive, but it is the only one that works consistently. We'll try to find a workaround, but we're limited by how the data is served, and there is only so much we can do in some situations.

That being said, we're not giving up on finding a solution that's less expensive, but I can't share ETA now.

**Comment by mikemorcerf** [comment]
Unfortunately it seems Google discontinued the feature to retrieve all `direct_links` at once.
We will keep monitoring to see if Google reimplements that in the near future. If that doesn't happen, then we will remove this feature from the API as well to reflect these changes on the Google layout.
For the time being, we have placed a disclaimer on the [Google Shopping API documentation](https://serpapi.com/google-shopping-api#direct-link-parameter-search-notes), and [Google Shopping Playground](https://serpapi.com/playground?engine=google_shopping&q=coffee) to convey this information.

[Google Shopping API documentation](https://serpapi.com/google-shopping-api#direct-link-parameter-search-notes):
![Image](https://github.com/user-attachments/assets/e0765ab1-823e-4630-b48c-b1ac3b6495d6)

[Google Shopping Playground](https://serpapi.com/playground?engine=google_shopping&q=coffee)
![Image](https://github.com/user-attachments/assets/d9fabcc2-789c-4618-8333-6ab4b4e69c7d)

**Comment by hilmanski** [comment]
I've reduced the priority of this ticket since Google doesn't provide the links at once anymore on their side.

**Comment by alexbarron** [comment]
Another customer asked about this:

[Front](https://app.frontapp.com/open/cnv_1fpeevrw?key=4o8DZlhMsWh4hF2bYxQw4-vD0v4IyOC4)

**Comment by DanielLDorn** [comment]
Hey, I love the idea of this, as it has become very expensive for my use case to use the google shopping api combined with the immersive product api, but I am getting empty result sets from queries with this engine. Is this currently working?

**Comment by hilmanski** [comment]
Hi @DanielLDorn , if you're talking about the Google Shopping Light API, you're correct. We currently have an issue with this new API. You can follow the updates here: https://github.com/serpapi/public-roadmap/issues/2847

**Comment by alexbarron** [comment]
Another report:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/215469931683396?view=List)

**Comment by schaferyan** [comment]
Our high volume enterprise customer requested `direct_link`, as well as `description`. They'd like these for Google Shopping Light API if possible.

[Customer](https://serpapi.slack.com/archives/C07PGJ8G70R/p1756396332823159?thread_ts=1756332011.857339&cid=C07PGJ8G70R)

**Comment by schaferyan** [comment]
I think this is potentially possible based on [this](https://serpapi.slack.com/archives/C07TYRMCHSL/p1755899581255489?thread_ts=1755732035.639679&cid=C07TYRMCHSL) internal conversation, so I'll move it back to `prioritized`.

**Comment by AutumroseS** [comment]
[Internal Reports](https://docs.google.com/spreadsheets/d/1xuU6DqocrrhHv6WmPl-XYqooB7xKsDX2z0tTByMOrHo/edit?usp=sharing)
